services:
  - type: web
    name: spin-and-earn-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        value: "*"
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: REFERRAL_BONUS_AMOUNT
        value: 25
      - key: REFERRAL_BONUS_REFERRER
        value: 10
      - key: REFERRAL_CODE_LENGTH
        value: 8
